### PR TITLE
Replace yoda.mp3 with much longer yoda.mp3

### PR DESCRIPTION
**Pull request by acidiclight**
This PR replaces the original yoda death sound with an MP3 version of this video:

https://www.youtube.com/watch?v=f_N2BWhOHlk

This is in response to a suggestion on Mastodon which can be found here:
https://mastodon.social/@ryankage/111859477990388115

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
I feel like there should be a 1/10 chance of that playing instead

**Comment by acidiclight** [comment]
hmmm I'll have to look at the actual code and see if I can do that, but, yeah, good idea. Maybe I'll look at it later today

**Comment by acidiclight** [comment]
Okay, I overestimated how complicated it'd be to do that. IAbout to commit soon.

**Review by Zaprit — APPROVED** [review]
LGTM :+1:

**Pull request merged**
